/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pirate.Boundary.UserInterface;

import java.awt.Color;

/**
 *
 * @author BEN JAAFAR
 */
public class mainTest extends javax.swing.JFrame {

    /**
     * Creates new form mainTest
     */
    public mainTest() {
        initComponents();
        lifePanel1.setColot(Color.yellow);
        lifePanel2.setColot(Color.blue);
        pion1.setColor(Color.yellow);
        pion2.setColor(Color.blue);
        
        customLayeredPanel1.setLayer(pion1, 2);
        customLayeredPanel1.setLayer(pion2, 2);
        customLayeredPanel1.setLayer(casePanel1, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lifePanel1 = new com.mycompany.pirate.LifePanel();
        lifePanel2 = new com.mycompany.pirate.LifePanel();
        customLayeredPanel1 = new com.mycompany.pirate.Boundary.UserInterface.CustomLayeredPanel();
        pion1 = new com.mycompany.pirate.Pion();
        pion2 = new com.mycompany.pirate.Pion();
        casePanel1 = new com.mycompany.pirate.Boundary.UserInterface.CasePanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout lifePanel1Layout = new javax.swing.GroupLayout(lifePanel1);
        lifePanel1.setLayout(lifePanel1Layout);
        lifePanel1Layout.setHorizontalGroup(
            lifePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );
        lifePanel1Layout.setVerticalGroup(
            lifePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lifePanel2Layout = new javax.swing.GroupLayout(lifePanel2);
        lifePanel2.setLayout(lifePanel2Layout);
        lifePanel2Layout.setHorizontalGroup(
            lifePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        lifePanel2Layout.setVerticalGroup(
            lifePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        pion1.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout pion1Layout = new javax.swing.GroupLayout(pion1);
        pion1.setLayout(pion1Layout);
        pion1Layout.setHorizontalGroup(
            pion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pion1Layout.setVerticalGroup(
            pion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        customLayeredPanel1.add(pion1);
        pion1.setBounds(230, 80, 20, 20);

        pion2.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout pion2Layout = new javax.swing.GroupLayout(pion2);
        pion2.setLayout(pion2Layout);
        pion2Layout.setHorizontalGroup(
            pion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pion2Layout.setVerticalGroup(
            pion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        customLayeredPanel1.add(pion2);
        pion2.setBounds(390, 80, 20, 20);

        javax.swing.GroupLayout casePanel1Layout = new javax.swing.GroupLayout(casePanel1);
        casePanel1.setLayout(casePanel1Layout);
        casePanel1Layout.setHorizontalGroup(
            casePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        casePanel1Layout.setVerticalGroup(
            casePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        customLayeredPanel1.add(casePanel1);
        casePanel1.setBounds(280, 110, 49, 47);

        jButton1.setText("TakeDamage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lifePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(lifePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(customLayeredPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lifePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lifePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(331, 331, 331)
                .addComponent(jButton1)
                .addGap(0, 35, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(customLayeredPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lifePanel1.perdreVie();
        lifePanel2.perdreVie();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.pirate.Boundary.UserInterface.CasePanel casePanel1;
    private com.mycompany.pirate.Boundary.UserInterface.CustomLayeredPanel customLayeredPanel1;
    private javax.swing.JButton jButton1;
    private com.mycompany.pirate.LifePanel lifePanel1;
    private com.mycompany.pirate.LifePanel lifePanel2;
    private com.mycompany.pirate.Pion pion1;
    private com.mycompany.pirate.Pion pion2;
    // End of variables declaration//GEN-END:variables
}
